### PR TITLE
Add README with image gallery and links.

### PR DESCRIPTION
**Pull request by donovankeith**
Added README.md with images and links to shaders to make it easier for non-programmers to get an overview of the shaders on GitHub.

### CODE REVIEW

**Review by paddy — CHANGES_REQUESTED** [review]
Open Beta link is out of date, as that thread was closed a year ago.  Perhaps better to provide forum category link for browsing/reporting of any issues with Redshift OSL: https://redshift.maxon.net/category/41/bugs-redshift-osl

File also contains numerous broken links which appear to be copy/paste errors and should be removed completely.  _e.g._ `[### ThinFilmInterference.jpg](### ThinFilmInterference.jpg)`

**Comment by donovankeith** [comment]
> Open Beta link is out of date, as that thread was closed a year ago. Perhaps better to provide forum category link for browsing/reporting of any issues with Redshift OSL: https://redshift.maxon.net/category/41/bugs-redshift-osl

Fixed. Is there an Intro tutorial / usage instructions you'd like me to link? No worries if not.

> File also contains numerous broken links which appear to be copy/paste errors and should be removed completely. _e.g._ `[### ThinFilmInterference.jpg](### ThinFilmInterference.jpg)`

Good catch! Fixed.

**Comment by paddy** [comment]
Please review each section.  Some orphaned OSL file names (no section, no link) and a zip file name.  TextureNoTile has entire section with only example images -- is that intentional?  I think the headings should be reserved for shaders and any supplemental examples etc should be single-line links underneath the link to the OSL file, without being embedded if possible as that just adds clutter.

**Comment by donovankeith** [comment]
Now generating README via python script to avoid human error (I can include it in the repo if you'd like, or create another repo to maintain it).

- Renamed some files to unify naming scheme so it could be easily ingested by a script.
- Added Emoji "icons" for Shaders, Zips, and Example Images.
- Secondary example images now presented as links.

**Comment by paddy** [comment]
Maybe need discussion amongst dev team regarding inclusion of templates/code.  Most people pulling this repo are interested in the shaders only and such supplementary tools maybe belong in a separate repository. However, that adds its own headaches.  If we did include the code in this repo, then we should restructure with subdirectories ("shaders" and "misc"/"tools"/whatever) .  Even without that, it may be cleaner to have shaders in a subdirectory anyway, so that direct links to this repo on the web will land on a short directory listing plus the README.  Anyway....  Out of scope for this PR!

On that note, "README" is also appearing in README.md.  I think the script is not handling self-exclusion.  This would be resolved by a future restructure, but for now please just add an exception.

I also missed your question about the spec/tutorial link.  Unsure about tutorials, but the spec is good.  Direct link is https://raw.githubusercontent.com/AcademySoftwareFoundation/OpenShadingLanguage/main/src/doc/osl-languagespec.pdf

If you address the README self-inclusion then I'm happy to merge.  Link to OSL spec is useful but optional. :)

**Comment by donovankeith** [comment]
Removed README from automatic generation. Create a public repo to store my docs generator script.

https://github.com/donovankeith/RedshiftOSLShadersDocGen

**Review by paddy — APPROVED** [review]

**Pull request merged**
