### PR TITLE
Updates to TriplanarCoordinates, Blur, and a new HeightWeights OSL

### PR DESCRIPTION
**Pull request by wuzelwazel**
Add support for using rest attributes "stick" the triplanar coordinates to a deforming mesh. Add more blur weights (exponential & power) for the blur shader. Introduce the HeightWeights shader that can be used to use height textures to generate blend weights for material or color layer shaders.

Small bug fixes.

### CODE REVIEW

**Comment by paddy** [comment]
When adding new shaders, please also update README.md with a new entry.

**Comment by paddy** [comment]
Consider `#include "vector4.h"` instead of hardcoding the `vector4` implementation, as this is already distributed with Redshift OSL.

**Comment by wuzelwazel** [comment]
> Consider `#include "vector4.h"` instead of hardcoding the `vector4` implementation, as this is already distributed with Redshift OSL.

Thanks. Is there a publicly available method for finding out what additional libraries are included with Redshift OSL?

**Comment by paddy** [comment]
OSL headers shipped with Redshift are installed in `osl/include` under Redshift's core data path.

**Pull request merged**
